---
application:
    name: 'bc-bot'
    project: 'BCBot'
    organization: 'QoveryCommunity'
routers:
    - name: 'main-process'
      routes:
          - application_name: 'bc-bot'
            paths:
                - '/*'
